### ISSUE TITLE
how to host?

### ISSUE THREAD

**Issue by DEV1234simple** [yeazin/Zooming-cls#1]

**Comment by yeazin** [comment]
We are working on this projects .
update will be coming soon.
You can host the current development in whatever you prefer.
like in ' Linux server or cloud solution (AWS,Digital Ocean)

**Comment by theprogrammingking** [comment]
but can tou tell the procedure after your updates pls nice project by the way

**Comment by theprogrammingking** [comment]
can you host it and show demmo pls?

**Comment by yeazin** [comment]
> but can tou tell the procedure after your updates pls nice project by the way

You can deploy the project in heroku or python anywhare . 
I will update the further improvement soon as I am working on a large new project.

**Comment by yeazin** [comment]
> can you host it and show demmo pls?

Yup , I will

**Comment by theprogrammingking** [comment]
yes please

**Comment by theprogrammingking** [comment]
hey can you make a apk to website converter it would be helful for me and others if you can do it thanks

**Comment by yeazin** [comment]
You need the application as a mobile Application ?

**Comment by theprogrammingking** [comment]
nope a apk to website converter like it would personally help me also

**Comment by theprogrammingking** [comment]
can you add the link of this application really eager to test it out
